# Generated by Django 4.2.13 on 2024-06-08 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('account_money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_date', models.DateField()),
                ('account_active_date', models.DateField()),
                ('is_cheque', models.BooleanField()),
                ('overdraft', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('BranchName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=30)),
                ('assets', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_tel', models.CharField(max_length=20)),
                ('customer_add', models.CharField(max_length=30)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_tel', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=30)),
                ('contact_relation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('loan_money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.loan')),
            ],
        ),
        migrations.CreateModel(
            name='AccountLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateField(auto_now_add=True)),
                ('log_money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('log_type', models.CharField(max_length=30)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='BranchName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.branch'),
        ),
        migrations.CreateModel(
            name='CustomerAndLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.customer')),
            ],
            options={
                'unique_together': {('customer_id', 'loan_id')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAndAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.account')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bank.customer')),
            ],
            options={
                'unique_together': {('account_id', 'customer_id')},
            },
        ),
    ]
